### ISSUE TITLE
vifmimg freezes when used with vifm inside tmux

### ISSUE THREAD

**Issue by wimstefan** [cirala/vifmimg#42] opened 2022-02-19 15:00 UTC
I have the latest vifmimg scripts installed from the repository with `make install` and use the recommend configuration in my vifmrc. `ueberzug` version is `18.1.9` and my system is running Gentoo.
When I invoke vifm inside tmux with `vifmrun` and scroll to a file which is supported by vifmimg the terminal freezes and I can't do anything anymore. Only killing vifm helps. The terminal is `kitty` btw. but the same happens with `alacritty` ...

Doing the same outside tmux is no problem at all. How can I configure vifmimg that it at least throws an error message and let's me continue working?

**Comment by kwand** [comment] 2022-02-21 09:06
I can confirm that I'm having the same problem on Arch Linux (latest packages from AUR)

**Comment by chedieck** [comment] 2022-06-10 22:40
I was having the same problem and managed to solve it: the issue was with `ueberzug`.
I removed it together with its exclusive dependencies (Arch Linux):
```
pacman -Rs ueberzug
```
Then installed it back, but through pip:
```
pip3 install ueberzug
```

**Comment by wimstefan** [comment] 2022-06-13 00:57
Thanks for reporting how you solved it for your system. Will try it as soon as I'm at my computer again - in two weeks time.
What I know so far is that I've installed and tried ueberzug both ways: as system package (Gentoo) and via pip. It didn't work anyway in kitty but it does now with wezterm ...

**Comment by thimc** [comment] 2022-08-12 00:11
Seems like @chedieck answer fixes this issue. I'll close it since it's not a vifmimg issue.

**Closed as completed by thimc** 2022-08-12 00:11 UTC
